"""Upload scheduler: upload branded clips to YouTube via Data API v3 with a
future publishAt date, so content stays buffered even if the laptop is offline.

Auth: OAuth 2.0 desktop flow. Put client_secret.json in the project root
(from Google Cloud Console -> APIs & Services -> Credentials). The first run
opens a browser to authorize; the token is cached in token.json.

Scheduling: each new upload is set to publish `buffer_days` from now, at
`publish_hour`, spreading multiple clips one day apart so the queue drains
gradually.
"""
import os
import sys
import glob
from datetime import datetime, timedelta, timezone
from core.utils import load_config, setup_logger, storage_paths, read_json, write_json

LOG = setup_logger("uploader")

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
UPLOAD_STATE = "upload_state.json"  # tracks which files were uploaded + next slot


def get_service(cfg):
    """Build an authenticated YouTube Data API client."""
    try:
        from google.oauth2.credentials import Credentials
        from google_auth_oauthlib.flow import InstalledAppFlow
        from google.auth.transport.requests import Request
        from googleapiclient.discovery import build
    except ImportError:
        LOG.error("Google API libs missing. Run: pip install -r requirements.txt")
        return None

    creds = None
    token_file = cfg.get("token_file", "token.json")
    if os.path.exists(token_file):
        creds = Credentials.from_authorized_user_file(token_file, SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            secret = cfg.get("client_secret", "client_secret.json")
            if not os.path.exists(secret):
                LOG.error(f"Missing {secret}. Download OAuth desktop credentials from Google Cloud.")
                return None
            flow = InstalledAppFlow.from_client_secrets_file(secret, SCOPES)
            creds = flow.run_local_server(port=0)
        with open(token_file, "w", encoding="utf-8") as f:
            f.write(creds.to_json())
    return build("youtube", "v3", credentials=creds)


def next_publish_time(cfg, state):
    """Compute the next publishAt (RFC3339 UTC). Spread 2 videos per day."""
    slot = state.get("slots_used", 0)
    
    # Default buffer_days to 1 instead of 5
    buffer_days = cfg.get("buffer_days", 1)
    
    # Karena kita ingin upload 2 video per hari:
    # Slot 0 dan 1 -> Hari ke-1
    # Slot 2 dan 3 -> Hari ke-2, dst.
    day_offset = slot // 2
    base = datetime.now(timezone.utc) + timedelta(days=buffer_days + day_offset)
    
    # 05:00 UTC = 12:00 Siang WIB (Video Pertama hari itu)
    # 12:00 UTC = 19:00 Malam WIB (Video Kedua hari itu)
    chosen_hour = 5 if slot % 2 == 0 else 12
    
    dt = base.replace(hour=chosen_hour, minute=0, second=0, microsecond=0)
    return dt


def upload_one(service, video, cfg, publish_at):
    """Upload a single video, scheduled private->public at publish_at."""
    from googleapiclient.http import MediaFileUpload
    
    # Read custom metadata if available
    base_name = os.path.basename(video).replace("_branded.mp4", "")
    clips_dir = os.path.join(cfg.get("storage_dir", "storage"), "clips")
    meta_path = os.path.join(clips_dir, f"{base_name}_metadata.json")
    
    title = base_name
    desc_addon = ""
    if os.path.exists(meta_path):
        meta = read_json(meta_path, {})
        title = meta.get("title", title)
        original_url = meta.get("original_url") or meta.get("channel_url", "")
        if original_url:
            desc_addon = f"\n\nCredit & Video Asli: {original_url}"
            
    body = {
        "snippet": {
            "title": title[:95],
            "description": f"Auto-generated by KnowClips.\n#shorts #edukasi #fakta{desc_addon}",
            "tags": ["knowclips", "shorts", "edukasi", "fakta", "wawasan"],
            "categoryId": str(cfg.get("category_id", "27")),
        },
        "status": {
            "privacyStatus": "private",
            "publishAt": publish_at.isoformat(),
            "selfDeclaredMadeForKids": False,
        },
    }
    media = MediaFileUpload(video, chunksize=-1, resumable=True)
    LOG.info(f"Uploading '{title[:45]}' (publish {publish_at.date()} {publish_at.hour}:00 UTC)")
    request = service.videos().insert(part="snippet,status", body=body, media_body=media)
    response = None
    retry_count = 0
    MAX_RETRIES = 5
    
    while response is None:
        try:
            status, response = request.next_chunk()
            if status:
                LOG.info(f"  ...{int(status.progress() * 100)}%")
            retry_count = 0  # reset on successful chunk
        except Exception as e:
            retry_count += 1
            if retry_count > MAX_RETRIES:
                raise Exception(f"Failed to upload after {MAX_RETRIES} retries: {e}")
            LOG.warning(f"  Network error during upload (retry {retry_count}/{MAX_RETRIES}). Waiting {2**retry_count}s...")
            import time
            time.sleep(2 ** retry_count)
            
    LOG.info(f"  done -> https://youtu.be/{response['id']}")
    return response["id"]


def run(cfg):
    paths = storage_paths(cfg)
    videos = sorted(glob.glob(os.path.join(paths["output"], "*_branded.mp4")))
    if not videos:
        LOG.info(f"No branded videos to upload in {paths['output']}")
        return []

    state = read_json(UPLOAD_STATE, {"uploaded": [], "slots_used": 0})
    uploaded_set = set(state.get("uploaded", []))
    pending = [v for v in videos if os.path.basename(v) not in uploaded_set]
    if not pending:
        LOG.info("All branded videos already uploaded.")
        return []

    service = get_service(cfg)
    if service is None:
        return []

    done = []
    for video in pending:
        publish_at = next_publish_time(cfg, state)
        try:
            vid_id = upload_one(service, video, cfg, publish_at)
        except Exception as e:  # noqa: BLE001
            LOG.error(f"Upload failed for {os.path.basename(video)}: {e}")
            continue
        uploaded_set.add(os.path.basename(video))
        state["slots_used"] = state.get("slots_used", 0) + 1
        state["uploaded"] = sorted(uploaded_set)
        write_json(UPLOAD_STATE, state)
        done.append(vid_id)
    LOG.info(f"Scheduled {len(done)} upload(s).")
    return done


def main():
    cfg = load_config()
    run(cfg)


if __name__ == "__main__":
    main()
